### ISSUE TITLE
Top3Things not showed on Home page

### ISSUE THREAD

**Issue by kuvakina** [LeedsCC/Helm-PHR-Project#102]
On **helm-dev** and **mango-cookie** I added 2 of 3 Top3Things: https://www.screencast.com/t/w6SyLbnk3Lz , but on Home page I see this: https://www.screencast.com/t/Pbltpi0HOTh

When I'm on the Top3Things page, I see like this:
**preview** : https://www.screencast.com/t/kb7wFVWxFiMP 
**response** : https://www.screencast.com/t/EtVsLCPSX

When I om Home page, for Top3Things I see like this:
**preview** : https://www.screencast.com/t/e1FZX417ie 
**response** : https://www.screencast.com/t/bG7kzFNTHo

**Comment by kuvakina** [comment]
Dima is waiting for @robtweed  approve of PR:  https://github.com/QEWD-Courier/QEWD-Courier/pull/35

**Comment by PhilBarrett** [comment]
This has now been superseded by  issue #1 migrate top3 things onto openEHR backend
