### ISSUE TITLE
Profile enhancements

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#11]
In the user profile, please 

- prefix PHR with "User Role:" and prefix "Date of Birth:" to date
- invoke user.dateOfBirth value and convert from UTC to regular date

**Comment by PhilBarrett** [comment]
@kuvakina could we get an update on this one please. thanks

**Comment by kuvakina** [comment]
@PhilBarrett 

Checked myhelm.org and there everything is OK: https://www.screencast.com/t/gG2yrRI6

Or we have to add the same for http://dev.ripple.foundation:8000 : https://www.screencast.com/t/unSOmA0HRF ?

**Comment by PhilBarrett** [comment]
After speaking with Tony, we are closing this issue, may need to reopen in future.
