### ISSUE TITLE
Helm MPI service

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#110]
Idea here is to set up the basis of a MPI view including Multi Patient View and hooks to the FHIR based MPI service, for GET demographics. 

This view is limited to IDCR role and a Helm administrator system.

**Comment by PhilBarrett** [comment]
Hi @richardcbrown Could you provide an update in here please along with the latest version of the code and where it's been deployed to. We need to test this in our environments.

**Comment by PhilBarrett** [comment]
@robtweed  can we get your view on this please, to be able to deploy the Helm MPI service . Conversation between yourself and Tony required.

**Comment by richardcbrown** [comment]
Hi @PhilBarrett, the MPI service is still under review, there's a set of review changes waiting review then it should be ready to be merged in. PR can be found here https://github.com/QEWD-Courier/QC-MPI-Microservice/pull/1

As for deployment I need to catch up with Rob Organ about the progress of YHCR development. What infrastructure is the helm test environment running on?

**Comment by tony-shannon** [comment]
thanks @richardcbrown , have merged that well worked PR, thank you
Need to chat with @robtweed to compare/contrast between MS MPI now
FYI Helm dev is running Docker on Ubuntu, staging and production env are similar

**Comment by PhilBarrett** [comment]
Descoped by LCC, closing
