### ISSUE TITLE
Helm-dev bugs/issues

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#113]
- [x] top 3 things detail view header showing "problem/diagnosis"
 - [x] top 3 things create not working.
![Screen Shot 2019-03-25 at 11.49.39.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206456f66b7191a379ee0c2f58415c47be5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecd5bf34ae54a5da3163662f43b.png)

**Comment by tony-shannon** [comment]
logout issue needs fix

**Comment by BogdanScherban** [comment]
Create was fixed and work correctly.

Edit functionality haven't fixed yet because of this issue:
https://github.com/PulseTile/PulseTile-RA/issues/63

**Comment by tony-shannon** [comment]
> Create was fixed and work correctly.
> 
> Edit functionality haven't fixed yet because of this issue:
> [PulseTile/PulseTile-RA#63](https://github.com/PulseTile/PulseTile-RA/issues/63)

I assume you mean wrt Top 3 things , can also you comment on the others listed please @BogdanScherban

**Comment by BogdanScherban** [comment]
@tony-shannon 
This problem (Create and Edit errors) was common for all our plugins, not only for TopThreeThings.

Yesterday I fixed creation and checked it at all plugins (Allergies, Contacts, Problems, Vaccinations, TopThreeThings, Medications and Patients)

Editing is also common problem for all plugins. I described this issue totally for Francois and need in his help.

**Comment by BogdanScherban** [comment]
> logout issue needs fix
> caching clearout needs check +/- fix
Can we create new issue for these? I'm not understand the problem with logout: client side clean token and data in local storage. Should we clean Cookie and Storage totally?

> empty tables issue https://snag.gy/p9TCNh.jpg - should say No Records found
OK, it will be added

**Comment by tony-shannon** [comment]
Caching issue is already on the board https://github.com/LeedsCC/Helm-PHR-Project/issues/99

**Comment by tony-shannon** [comment]
and Logout has been added as an issue here https://github.com/LeedsCC/Helm-PHR-Project/issues/114

**Comment by kuvakina** [comment]
- [ ] Add expand button for Problems / Issues
- [ ] Add expand button for Medications
- [ ] Add expand button for Vaccinations
- [ ] Add expand button for Contacts
- [ ] Add expand button for Allergies
- [ ] Add expand button for Top3Things

**Comment by BogdanScherban** [comment]
@kuvakina 
Alexandra, these two had been done:
- top 3 things detail view header showing "problem/diagnosis"
- top 3 things create not working.

**Comment by PhilBarrett** [comment]
> * [ ]  Add expand button for Problems / Issues
> * [ ]  Add expand button for Medications
> * [ ]  Add expand button for Vaccinations
> * [ ]  Add expand button for Contacts
> * [ ]  Add expand button for Allergies
> * [ ]  Add expand button for Top3Things

These are now out of scope for Helm so moved to https://github.com/PulseTile/PulseTile-RA/issues/67
