### ISSUE TITLE
need logout to be clean & automated after timeout

### ISSUE THREAD

**Issue by tony-shannon** [LeedsCC/Helm-PHR-Project#114]
please ensure logout helps clear cache
+ if user leaves application for a while that login token cleared automatically

thanks
T

**Comment by PhilBarrett** [comment]
@BogdanScherban can we get an update on this please

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 

Now we have two cases, when user can use logout.

1) If user want to Sign out, he can click on Sign Out at the user panel:
https://drive.google.com/file/d/11zDvWNzPnfBo-rL8CUh1T7l_G2_x7S6m/view?usp=sharing

2) If user leave the page, and his token expired in this time. In this case modal window will open. If user click on "Login again", he will be redirected on the login page:
https://drive.google.com/file/d/1CtIsZYiQkH2O_lJ6sJV9-4P5ziNg9suJ/view?usp=sharing

In **both** cases local storage, session storage and cookie will be cleaned automatically.

**Comment by tony-shannon** [comment]
great thank you @BogdanScherban
