### ISSUE TITLE
Helm Responsive view testing

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#119]

**Comment by kuvakina** [comment]
For some reason I have this message:
![Screenshot_20190403-154057_Chrome.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5badf10d7690fd0011f09889/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cd791277206455f67f20d0b4179c4a690e020a5cb053181d1ba6acda6fb4bc2e75d80d58b8d2680973946e40a9ec821fb602ef29881ad3b3ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4ecc5aff4de14e51a2163671ab.jpg)

**Comment by kuvakina** [comment]
Menu button and how menu shown like this (you can open menu, but to close it you don't see button)
![Screenshot_20190403-154127_Chrome.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5badf10d7690fd0011f09889/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cd791277206455f67f21d7b4179c4a690e020a5cb053181d1ba6acda6fb4bc2e75d80d58b8d2680973946e40a9ec821fb602ef29881ad3b3ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4ecc5aff4de34e5ca1153671ab.jpg)
![Screenshot_20190403-155708_Chrome.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5badf10d7690fd0011f09889/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cd791277206455f67e27d5bb179c4a690e020a5cb053181d1ba6acda6fb4bc2e75d80d58b8d2680973946e40a9ec821fb602ef29881ad3b3ae965e82b96371b8d6d6056b5c17129bfe543fa19c4ecc5aff4de34e5ca11a3171ab.jpg)

**Comment by kuvakina** [comment]
When create T3T, buttons Complete and Close not tied with form
![Screenshot_20190403-154254_Chrome.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5badf10d7690fd0011f09889/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cd791277206455f67f22d0b7179c4a690e020a5cb053181d1ba6acda6fb4bc2e75d80d58b8d2680973946e40a9ec821fb602ef29881ad3b3ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4ecc5aff4de24c51a5123571ab.jpg)

**Comment by kuvakina** [comment]
Make this window responsive:
![Screenshot_20190403-155921_Chrome.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5badf10d7690fd0011f09889/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cd791277206455f67e29d7b2179c4a690e020a5cb053181d1ba6acda6fb4bc2e75d80d58b8d2680973946e40a9ec821fb602ef29881ad3b3ae965e82b96371b8d6d6056b5c17129bfe543fa19c4ecc5aff4de54d56a4143471ab.jpg)

**Comment by tony-shannon** [comment]
@BogdanScherban can you please action these asap

**Comment by BogdanScherban** [comment]
@tony-shannon 
It haven't been done because I see this issue only now. It will be done tomorrow.

**Comment by BogdanScherban** [comment]
@tony-shannon 

What have been done today:
1) Modal window in mobile mode (both issues);
2) Top part of topbar  in mobile mode;
3) Low part of topbar  in mobile mode;
4) Sidebar in mpbile mode.

Results on the video:
https://drive.google.com/file/d/1A3hPYAdRXqu3GAsei4FW8Yg9pAEV1mC_/view?usp=sharing

**Comment by kuvakina** [comment]
@PhilBarrett Bogdan fixed mobile view issues mentioned here. Can we close this one?
