### ISSUE TITLE
Adding "Feeds" to summary screen

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#12]
- Add feeds to Patient Summary view only, when the user logs in 
- set Feeds on as Default view in Cog wheel Settings

**Comment by PhilBarrett** [comment]
@kuvakina can you confirm this is completed please after testing

**Comment by kuvakina** [comment]
@PhilBarrett 

I've checked it. It doesn't set as default. Bogdan will change it after he finishes the current task.

**Comment by BogdanScherban** [comment]
It has been done. Current Helm-version has Feeds in summary screen

**Comment by PhilBarrett** [comment]
Reviewed and working fine. thanks @BogdanScherban

**Comment by PhilBarrett** [comment]
@robtweed Working on dev, but not staging. Query if related to PT build version

**Comment by PhilBarrett** [comment]
@kuvakina  We're getting a second Feed appearing on the summary screen with the latest build on Staging, taken from 8000. So a duplicate of the same feed. Can you take a look please.

**Comment by kuvakina** [comment]
@PhilBarrett 
I see only Feeds like this for "old" user: https://www.screencast.com/t/82Na3xsN

And I don't have feeds at all for new users: https://www.screencast.com/t/ir3Xh4jmfej

Could it be related to this issue: #34 (#17 )?

**Comment by PhilBarrett** [comment]
Hi @kuvakina I've tested this on a new user with an NHS number that hadn't been used before and feeds were being correctly added by QEWD. However they didn't appear on the patient summary screen and when I clicked on the cog, it displayed 3 feeds boxes (duplications). We believe this remains a PulseTile related issue and needs investigation please

**Comment by BogdanScherban** [comment]
@PhilBarrett 
Could you please share the screenshot with (at your machine):
1) Feeds boxes duplication;
2) Results of feeds-request.

For example - result at 8000:
![FEEDS.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb3796441a5980011efd33d/125516c66e82c728ace21e0d46ceb1bf07b1c1e5cdf9ad4cae58f3806b1c65262b05a02e23d0e57fbd417a540b5f4ea5420d5647a9af8c39baa47e21d40854b088270a36d43703adbf881eba05ba258f4985b4bd8c49c9fa70.png)

I want to compare Feeds behavior at your machine and 8000.

**Comment by simongamester** [comment]
This need to be tested once latest QEWD version has been updated.

**Comment by BogdanScherban** [comment]
@robtweed 
Rob, could you please help with this issue?

Phil sent result of Feeds-request at his machine:
![Screen Shot 2018-10-29 at 10.07.22.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb3796441a5980011efd33d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456fa6b7191a379ef0c2b56415d4cbe5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecc58fe49e14b57a3153167f43b.png)

You can see that server returned five similar items. Probably, current user has 5 similar Feeds in the Database.

So, can we prevent possibility to create Feeds for repeated names for one user?

**Comment by PhilBarrett** [comment]
Linked with https://github.com/LeedsCC/Helm-PHR-Project/issues/17

**Comment by PhilBarrett** [comment]
This has been resolved and tested.

If you change the NHS Number of a user to one that's not been used before - it assumes it has to add a new feed record, which is held in the QEWD database, not the OpenEHR database

The POST API was modified so it doesn't create duplicates. 

Not an issue in Live anyway, more test account related.
