### ISSUE TITLE
Helm Styling

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#120]
After further testing, I've noticed a couple of style differences between React and ReactAdmin. 

- [x] Circles in the background of the headers aren't as per React style. 
- [x] Type face and font size appear slightly different.

@BogdanScherban have these being resolved as part of earlier bug fixes and are in the next build?

**Comment by PhilBarrett** [comment]
How it should look
![Screen Shot 2019-04-03 at 13.12.36.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77276454f06b7191a379ec0c2a53415c48be5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecd5cf442e74d52a41a3f66f43b.png)

Current version in helm-dev
![Screen Shot 2019-04-03 at 13.53.08.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77276454f06b7191a379ec0c2e52415f46be5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c3caa984ecd5cf442e74c56a21a316af43b.png)

**Comment by tony-shannon** [comment]
@BogdanScherban can you action please asap

**Comment by BogdanScherban** [comment]
@tony-shannon 
It haven't been done because I see this issue only now. It will be done tomorrow.

**Comment by BogdanScherban** [comment]
@tony-shannon 

>  Type face and font size appear slightly different.

It has been done today

**Comment by PhilBarrett** [comment]
Completed and tested fine
