### ISSUE TITLE
Top 3 things - few bugs

### ISSUE THREAD

**Issue by tony-shannon** [LeedsCC/Helm-PHR-Project#121]
- [x] After adding to top 3 things reload is needed to see the data (see A below)
- [x] needs create button for new Top 3 things, after first entry
- [ ] Editing values in text field , cursor moves , see here https://screencast-o-matic.com/watch/cqffDcZh8E

**Comment by tony-shannon** [comment]
see A above
after saving Top3things
![image](https://user-images.githubusercontent.com/939996/55571640-d2829a80-56fd-11e9-8a0f-8de327d6854c.png)
after reload
![image](https://user-images.githubusercontent.com/939996/55571654-da423f00-56fd-11e9-961e-19286d67891b.png)

**Comment by BogdanScherban** [comment]
@tony-shannon 

> needs create button for new Top 3 things, after first entry

It is fixed

> After adding to top 3 things reload is needed to see the data (see A below)

It is fixed.

> Editing values in text field , cursor moves , see here https://screencast-o-matic.com/watch/cqffDcZh8E

Here we need in Francois help. Besides this, I found a problem, which we didn't see earlier.
I'll create issue for Francois about it.

**Comment by BogdanScherban** [comment]
I created two issues to ask Francois help:
https://github.com/PulseTile/PulseTile-RA/issues/72
https://github.com/PulseTile/PulseTile-RA/issues/71

**Comment by PhilBarrett** [comment]
Closing off as covered elsewhere, see above
