### ISSUE TITLE
Data source naming convention

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#20]
- If the data is coming from DDS, please change to "GP" in Summary table
- change to "EtherCIS via Discovery" in Source Detail if data from DDS

**Comment by robtweed** [comment]
The source for data written to EtherCIS from Discovery is currently reported by QEWD as "GP".  If it needs to be displayed differently in the UI, can't PulseTile do the transformation of a value of "GP" to "EtherCIS via Discovery"?

**Comment by tony-shannon** [comment]
PulseTile could, but makes more sense to do that from QEWD, as it is being written as GP by QEWD

**Comment by PhilBarrett** [comment]
After discussion with Tony, preference is that QEWD transfers the data with "EtherCIS via Discovery" and then PulseTile displays that value in the source information, and transforms that to "GP" in the summary tables. The system information should state  "EtherCIS via Discovery".

1. QEWD transfers the data to pulsetile with the label  "EtherCIS via Discovery"
2. PulseTile transforms that for the summary table to "GP"
3. PulseTile shows  "EtherCIS via Discovery" in the system information (detail view).

**Comment by BogdanScherban** [comment]
@PhilBarrett or @tony-shannon 
Could you please clarify this issue:
1) Is it necessary for each row, where source is 'ethercis' like this one:
![11221122.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb3796441a5980011efd33d/125516c66e82c728ace21e0d46b9c5c871d3d2fbddabf301b44fff9e2c4533317346f6297186e67bea442c030c0e4bf841585647a9f08a7ef0b32e6c981e5ab38532022d8c6853beb2901eb70bbb258f4e85b1bb824cc6ea3f20f5c6.png)

2) "GP" - for ceil in the table row and "EtherCIS via Discovery" - for detail block?

**Comment by PhilBarrett** [comment]
> @PhilBarrett or @tony-shannon
> Could you please clarify this issue:
> 
> 1. Is it necessary for each row, where source is 'ethercis' like this one:
>    ![11221122.png](https://camo.githubusercontent.com/32a6b0312fd1626f7694712ed128a05af4541e79/68747470733a2f2f776166666c65696f2d6469726563742d75706c6f6164732d70726f64756374696f6e2e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f3562623337393634343161353938303031316566643333642f313235353136633636653832633732386163653231653064343662396335633837316433643266626464616266333031623434666666396532633435333333313733343666363239373138366536376265613434326330333063306534626638343135383536343761396630386137656630623332653663393831653561623338353332303232643863363835336265623239303165623730626262323538663465383562316262383234636336656133663230663563362e706e67)
> 2. "GP" - for ceil in the table row and "EtherCIS via Discovery" - for detail block?

In both Staging and Production, we have information coming from Primary Care (https://en.wikipedia.org/wiki/Primary_care), which is often shortened to GP (General Practitioner) via the Discovery Data Service (http://www.discoverydataservice.org). In the table view for information coming over from DDS, it says GP, this is fine. in the System information box within the detail of an entry, it should change to "EtherCIS via Discovery".

in 8000 DDS isn't connected, which isn't ideal but the feeds and information can stay as they are. @tony-shannon we should be moving DDS onto 8000 as a planned separate task

**Comment by PhilBarrett** [comment]
Closing out - descoped
