### ISSUE TITLE
When side bar menu is expanded, menu button should read 'X Close'

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#25]

**Comment by PhilBarrett** [comment]
As per title

**Comment by simongamester** [comment]
Discussion on whether this should be part of core, the theme or configurable within core:

a) Within core -> Change hard coded text for button directly in core
b) WIthin theme -> Apply content changes via css (content:) when sidebar toggles between open and closed state.
c) As a config -> Add open and close variables to theme config which contain 'Menu' and 'Close'. This would need to default to 'Menu' in the event that this config has not been set.

There was a wider discussion on whether a common approach to language should be considered and how multi-lingual functionality might be added to PulseTile moving forward. In such a case, language files would define the text for each button, form element and help text. Something to consider in the future.

**Comment by PhilBarrett** [comment]
Linked to https://github.com/PulseTile/PulseTile-React-Core/pull/242
