### ISSUE TITLE
Improved user logic for Top 3 Things creates

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#26]
Test User feedback (AW):

When filling in the Top 3 Things to know about me it won't let you exit unless you fill in all three, I think you should be able to fill in 1 or 2 and save.

Logic to be updated​

**Comment by PhilBarrett** [comment]
Adding default text "To be completed"

**Comment by tony-shannon** [comment]
that PR fixes this issue
https://github.com/LeedsCC/Helm-PHR-Project/issues/26
