### ISSUE TITLE
add chat facility to Helm for trial

### ISSUE THREAD

**Issue by tony-shannon** [LeedsCC/Helm-PHR-Project#3]
to add chat facility for users

**Comment by kuvakina** [comment]
@tony-shannon 

(From https://github.com/PulseTile/PulseTile-React-Core/issues/205 )

At the moment we are working on Helm PHR theme plugin + Automatic creation of the build, and plan to move to UI/Data Model tidy up.

So I wanted to ask what is the priority of this issue?

**Comment by tony-shannon** [comment]
Having trialled this, I know the effort to include the script is minimal
So suggest we include as a minor task during the "branding" sprint
thanks
Tony

**Comment by tony-shannon** [comment]
closed in error, sorry

**Comment by kuvakina** [comment]
@tony-shannon Ok, thank you

**Comment by PhilBarrett** [comment]
@simongamester Can we get an update for what you did on this please.

**Comment by PhilBarrett** [comment]
Still need to
 - [ ] customise view

**Comment by PhilBarrett** [comment]
![Screenshot_20181002-144943.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc781677216455f77f29d1b06af3006b1300051bff054a5556f9abd878f3b539268d0e58bcd4395f74cf3e44a5bbd749ba13a632c91edbe2e3d7158abd7f37ed998e48341f001b81fb553ca6914fcb5eff59ac.jpg)

**Comment by tony-shannon** [comment]
thanks @PhilBarrett 
PLease let me know what action you need from me
T
