### ISSUE TITLE
Change in logic when accepting terms and conditions

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#31]
Currently when the user first logs in, they are presented with terms and conditions to either accept or cancel. Cancelling logs them out and accepting allows the user into the application. 

However data is retrieved behind the modal and can be seen before the user responds to the T&C's question. responding to the T&C's accepting should trigger the retrieval

**Comment by kuvakina** [comment]
To solve this issue we have 3 options:

1) Make T&C modal wider: http://prntscr.com/l1bahx

2) Make background opacity thicker (0.9): http://prntscr.com/l1bb9m

3) Make full background opacity (1): http://prntscr.com/l1bbnc

Which one will be better?

**Comment by PhilBarrett** [comment]
Not sure on these. @simongamester can you provide a view on other options please?

**Comment by simongamester** [comment]
I'm not sure any of these would address the issue really I'm afraid. Changing the visibility of the background or the size of the modal could easily be reverted using developer tools. We need to trigger the modal before the information is retrieved from the server.

@PhilBarrett If this is a problem, we could consider placing this modal on the login screen itself i.e. before we redirect over to the Patient Dashboard? This would move the functionality out of PulseTile completely as the login screen is a static html page. The biggest drawback would be that we'd have to trigger the modal when they press the login button not knowing if they've been successfully logged in.

**Comment by PhilBarrett** [comment]
Yeah neither of these options ideal to be honest. Behaviour needs to be

User logs into application
User then sees  the one time T&C's
If they decline, it logs them out
If they accept it, the event is recorded then retrieves the record. 

Need a fix based on that logic please

**Comment by BogdanScherban** [comment]
@PhilBarrett
I understand this idea - it will be good. But login form isn't located in our part of project (in Core). 

![Screenshot from 2018-10-03 12-44-10.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb3796441a5980011efd33d/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f27b3dd5b068ee1036555b424fac53444d04bea6d37ef5f22e7a985959bc82385c71903a43ffe9874bbf01b323de4686e3ea8f5edcfa7f74b9dfd0126754505a9bf54f34a8934acd5bfe4ee4445da31a3365e4647b.png)

Do you know where login form is located?

**Comment by PhilBarrett** [comment]
Awaiting new build to be loaded by Rob

**Comment by PhilBarrett** [comment]
Tested and working as intended
