### ISSUE TITLE
tidy up Helm Data models at UI level

### ISSUE THREAD

**Issue by tony-shannon** [LeedsCC/Helm-PHR-Project#4]
to do based on changes needed for go live informed by this UX review
https://projects.invisionapp.com/d/main#/projects/prototypes/11007532

- [x] Patient Summary Page -rename Diagnosis to Problems issues
- [x] Problems/Issues Page- Detail- hide Terminology/Code  + hide Create/Edit buttons
- [x] Medications Page- Summary- hide Dose col & change Supply col to Date  + Create button -  on summary table
- [x] Medications Page- Detail - hide Dose Amount, Timing, Prescription (button), Cancel, Suspend, Order Edit (buttons), Prescription, Warnings, Change history tabs 
- [x] Contacts page -Summary- hide Next of Kin col (Summary Table), 
- [x] Allergies Page - Summary- hide Reaction col (Summary Table) + Create button
- [x] Allergies Page - Detail- change Reaction to Reaction/Description) + hide Edit button
- [x] Vaccinations page- Summary- switch Source col to right, Date col to middle + hide Create button
- [x] Vacciinations page- Detail- Vacc Date to Date, move comment up, move Source down to System info tab + Hide Edit 
- [ ] Top 3 things - tbd
- [x] System information tab - at bottom of all detail views - to include Source & Date information

**Comment by BogdanScherban** [comment]
@tony-shannon 

These issues have been done at the moment:
- Patient Summary Page -rename Diagnosis to Problems issues;
- Problems/Issues Page- Detail- hide Terminology/Code + hide Create/Edit buttons;
- Medications Page- Summary- hide Dose col & change Supply col to Date + Create button - on summary table;
- Medications Page- Detail - hide Dose Amount, Timing, Prescription (button), Cancel, Suspend, Order Edit (buttons), Prescription, Warnings, Change history tabs;
-  Contacts page -Summary- hide Next of Kin col (Summary Table),
- Allergies Page - Summary- hide Reaction col (Summary Table) + Create button
- Allergies Page - Detail- change Reaction to Reaction/Description) + hide Edit button

Tomorrow we will work on System information tabs in all headings and other issues, which aren't presented here.

**Comment by kuvakina** [comment]
UPD on 30.08:

We've done part of changes for the task Helm-desktop-data-model and tomorrow we're going to continue this issue

Were approved these pull-requests, that were necessary to check the work of Generator with new changes:
https://github.com/PulseTile-Plugins/Silver-Plugin-Vaccinations/pull/2
https://github.com/RippleOSI/Helm-PHR-Generator/pull/4
https://github.com/PulseTile/PulseTile-React-Core/pull/209

**Comment by tony-shannon** [comment]
thanks @BogdanScherban 
Based on chat yesterday Contacts should be excluded/hidden/removed for now
What about progress on Vaccinations ?

**Comment by BogdanScherban** [comment]
@tony-shannon 
In Vaccinations we are working on adding System Information panel at the moment. All other changes were done.

Regarding Contacts: yes, I remember, I'll hide Contacts after finishing with https://projects.invisionapp.com/d/main#/projects/prototypes/11007532

**Comment by BogdanScherban** [comment]
@tony-shannon 

I've solved the issue with Feeds-plugin automatically adding by the way:
- Core was updated for this possibility;
- Feeds-plugin was updated and saved as separate repository;
- Add sub-generator for Feeds-plugin to the Generator for Helm-PHR.

PRs for first two issues:
https://github.com/PulseTile/PulseTile-React-Core/pull/211
https://github.com/PulseTile-Plugins/Silver-Feeds-Plugin/pull/1

When they will be approved, I'll check work of Generator and create PR for it.

**Comment by tony-shannon** [comment]
> @tony-shannon

I've solved the issue with Feeds-plugin automatically adding by the way:

Core was updated for this possibility;
Feeds-plugin was updated and saved as separate repository;
Add sub-generator for Feeds-plugin to the Generator for Helm-PHR.
PRs for first two issues:
PulseTile/PulseTile-React-Core#211
PulseTile-Plugins/Silver-Feeds-Plugin#1

When they will be approved, I'll check work of Generator and create PR for it.

Sorry @BogdanScherban  that comment is not relevant to this issue, please clarify/edit

**Comment by kuvakina** [comment]
@tony-shannon 

Regarding this task: should we fix Top 3 Things? Or for now, we can consider this task as Done or move it to Backlog?

**Comment by PhilBarrett** [comment]
Marking as done, closing.
