### ISSUE TITLE
Title Bar in browser needs to say Helm

### ISSUE THREAD

**Issue by tony-shannon** [LeedsCC/Helm-PHR-Project#43]
see image

**Comment by tony-shannon** [comment]
![i592^pimgpsh_thumbnail_win_distr.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bae28b4d734ec0013e1f936/125516c66e82c728ace21e0d46e1c1c371bc93a082eeaf50ac62e49c3c4b257d280daf14678ced17bb4b68151d4d52be011a001ea9aacd39aca43922db0f5eeed43b5826956c14f8b88216bc54b323de1980a4a0980e91b6697abad2c51a7c0c0f0a88f65734a59a43ce5ff44de94e54ac11242e.jpg)

**Comment by simongamester** [comment]
I'm afraid this is not very straight forward. The title tag is initially set within the index.html file, is provided by the helm theme using the generator. You'll notice it says 'myHelm' for the first few seconds of loading.

HOWEVER, the browser title is then set via javascript when React initialises via an API call to /api/application. See screen:

![Screenshot 2018-10-06 at 16.34.53.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb37967f01e4d00110fba95/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417773e7952e32a64c5b27ef1112f4f5a5c5cb053181d1ba6acda6fb4bc2e75d80d58b8d2680973946e40a9ec821fb602ef29881ad3b3ae965e82b96371b8d6d6056b5c17129bfd5c3fa19c48c050f24be34e5ca21b3471ab.png)

I suspect this may be one for Rob, what do you think Tony?

Simon

**Comment by simongamester** [comment]
Mute the change.

**Comment by PhilBarrett** [comment]
Working on dev. Needs latest Dev build promoting onto Staging via @robtweed
