### ISSUE TITLE
T&C's appearing each login

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#44]
As a user, each time I log in, the Terms and Conditions for Helm appear requiring action before being able to access the record. 

This is a one time event at this time, not each time.

**Comment by robtweed** [comment]
Is this on the OpenId Connect Login screen (before you get the 2FA code form)?  If so, you need to discuss with Simon

**Comment by simongamester** [comment]
Add a cookie to store when users accept terms. Server side call to be enabled there after.

**Comment by simongamester** [comment]
Hi @PhilBarrett Just added a PR for this now. 
https://github.com/PulseTile-Plugins/Plugin-UserLogin_Theme-HelmPHR/pull/8

**Comment by PhilBarrett** [comment]
Tested working fine
