### ISSUE TITLE
Medications Field Mapping

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#45]
When logged in and I navigate to the detail view of a medication entry, Dose Description is void of information.

**Comment by PhilBarrett** [comment]
![Screen Shot 2018-10-10 at 16.20.07.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f36b7191a379e90c2951415f49be5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecb51f44ee14856a71b3f67f43b.png)

**Comment by robtweed** [comment]
This is a known issue that is understood by Ian and Christian - a limitation of EtherCIS.  Suggest you raise it with them again - Dose Timing and Dose Description are related in terms of this problem

**Comment by PhilBarrett** [comment]
@chevalleyc Could you take a look at this please upon your return. Thanks.

**Comment by chevalleyc** [comment]
Could you please relate this issue to an EtherCIS CR or create a new one with a scenario/example to reproduce it in my environment. Thanks!

**Comment by PhilBarrett** [comment]
Closing out - descoped from Helm project
