### ISSUE TITLE
Mobile experience - Helm logo and padding

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#48]
Tested on both Android (Samsung S9, Chrome) and iOS (iPhone 6, Safari+Chrome) 

The Helm Logo on login screen isn't responsive and bleeds over the circles with no padding.
![Screen Shot 2018-10-16 at 09.43.39.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f56b7191a378e60c2f52415c47be5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5f35aa984ecb51f043e34d57a1123762f43b.png)
![Screen Shot 2018-10-16 at 09.51.27.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f56b7191a378e60c2e50415d49be5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5f34aa984ecb51f043e34d57a1123767f43b.png)

**Comment by PhilBarrett** [comment]
Can we get an update in this issue please and the related PR if complete. Cheers

**Comment by PhilBarrett** [comment]
Hi @simongamester I've tested this and still encountering the issue. The helm text is overlapping the circles.

**Comment by simongamester** [comment]
@PhilBarrett I'll take a look...

**Comment by simongamester** [comment]
@robtweed @PhilBarrett  Just taken a look at the main.css on login.myhelm.org and I think it needs updating.  See comparison below:

https://www.diffnow.com/?report=06dbc

I think this is causing the padding issues as it addresses the live version is still running the smaller font size on the form elements.

Thanks,

Simon

**Comment by PhilBarrett** [comment]
Updated as moved onto React-Admin, checking if still an issue

**Comment by PhilBarrett** [comment]
Closing off due to change in scope from LCC and now moving to NHS Login.
