### ISSUE TITLE
Mobile experience - Helm home button placement

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#50]
Not centred. See screenshot

**Comment by PhilBarrett** [comment]
![Screen Shot 2018-10-16 at 09.44.54.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f56b7191a378e60c2f55415a4abe5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5f34aa984ecb51f043e34955a3123066f43b.png)

**Comment by PhilBarrett** [comment]
Also check URL

**Comment by simongamester** [comment]
Fixed in PR https://github.com/PulseTile-Plugins/Plugin-Helm-PHR-Theme/pull/15

**Comment by simongamester** [comment]
![Screenshot 2018-10-16 at 15.49.49.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb37967f01e4d00110fba95/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417773e7852e32a64c5b27df116224f5b565cb053181d1ba6acda6fb4bc2e75d80d58b8d2680973946e40a9ec821fb602ef29881ad3b3ae965e82b96371b8d6d6056b5c17129bfe5b3fa19c48c15ff64ae64550a31a3071ab.png)
