### ISSUE TITLE
Mobile experience - Feedback button

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#52]
The feedback button doesn't present in a user friendly manner

The feedback button doesn't work when clicked upon

**Comment by PhilBarrett** [comment]
![Screen Shot 2018-10-16 at 09.45.28.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f56b7191a378e60c2f54415d46be5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c3caa984ecb51f043e34b51a0123567f43b.png)

**Comment by simongamester** [comment]
[Uploading Screenshot 2018-10-16 at 15.49.49.png...]

**Comment by simongamester** [comment]
![screenshot 2018-10-16 at 15 49 49](https://user-images.githubusercontent.com/8059219/47025612-babd5700-d15b-11e8-870e-5fbc626eff25.png)

**Comment by simongamester** [comment]
Is this ok? I've set the z-index to appear above widgets on the dashboard.

![screenshot 2018-10-16 at 15 59 58](https://user-images.githubusercontent.com/8059219/47026961-73849580-d15e-11e8-8acb-338dc90213e2.png)

It could be positioned lower down the screen, however when the user scrolls to the bottom of the page, it would obscure the ripple logo, so suggest we leave as is:

![screenshot 2018-10-16 at 16 14 50](https://user-images.githubusercontent.com/8059219/47027068-a595f780-d15e-11e8-93bd-6c73e598f8a2.png)

**Comment by PhilBarrett** [comment]
Can you take a look at a smaller logo perhaps and see how it looks at the bottom please. Also you can see the copyright notice and RF logo aren't on one line. Perhaps move to the copyright logo instead might fix this.

**Comment by simongamester** [comment]
Maybe we could move the logo over to the left on mobile? Then the icon would fit quite nicely lower down in the bottom right space without overlapping?

**Comment by PhilBarrett** [comment]
https://github.com/PulseTile-Plugins/Plugin-Helm-PHR-Theme/pull/24

**Comment by PhilBarrett** [comment]
Working fine.
