### ISSUE TITLE
Mobile experience. Patient info goes missing

### ISSUE THREAD

**Issue by BogdanScherban** [LeedsCC/Helm-PHR-Project#53]
Patient information is absent in mobile version.
![123](https://user-images.githubusercontent.com/39263134/47164470-c6964e00-d300-11e8-8abb-07ea3304697c.png)

**Comment by Alena1508** [comment]
Hi @ tony-shannon,
I changed Helm for mobile according to mockups. Now we can see the username as in design (https://projects.invisionapp.com/d/main#/console/11007545/316291014/inspect).
It looks this way: http://prntscr.com/l8xn5m

An here I have a question. Arrow button on green background (http://prntscr.com/l8y0dd). But now you’re absent for design:
I would like to see what you are looking for in mockups (w / o patient info)?

**Comment by kuvakina** [comment]
Related to issue #264 https://waffle.io/RippleOSI/combined-development-view/cards/5bc73ff4fb924200570ec00b

**Comment by Alena1508** [comment]
This issue was fixed.
We change styles for patient's info area.

**Comment by PhilBarrett** [comment]
Tested and working as intended, thanks Alena
