### ISSUE TITLE
Selecting an entry from Patient Summary screen, doesn't open that entry in table view

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#56]
When you select a medication entry in the patient summary it should take you to the medication in the medication table, with detail open to the right of the table. This behaviour isn't working, see screencast.

**Comment by simongamester** [comment]
@BogdanScherban Could we get an update on this issue please?

**Comment by Alena1508** [comment]
Added some functionality to Core pages to fix the problem with selecting empty item from Patient Summary screen.
Now when user click on Medication item on Patient Summary screen he'll see the page with current item.
PR:  
1) https://github.com/PulseTile/PulseTile-React-Core/pull/273
2) https://github.com/PulseTile-Plugins/Silver-Plugin-Vaccinations/pull/6

**Comment by PhilBarrett** [comment]
Reviewed, working fine. Thanks.
