### ISSUE TITLE
When a table is loading, loading message is required

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#57]
See video

**Comment by PhilBarrett** [comment]
Update following d/w Rob Tweed. This is a PulseTile related issue that needs resolving

**Comment by Alena1508** [comment]
This PR https://github.com/PulseTile/PulseTile-React-Core/pull/272 - for current task.
I added functionality for "Loading ..." message  on all pages. When tables are loading user can see the message "Loading..."

**Comment by PhilBarrett** [comment]
Reviewed, working fine. thanks
