### ISSUE TITLE
Jenkins E2E tests for Helm update

### ISSUE THREAD

**Issue by kuvakina** [LeedsCC/Helm-PHR-Project#60]
because we make changes for Helm, we have to update Helm tests also.

**Comment by BogdanScherban** [comment]
Only one test worked incorrectly after Helm-version rebranding. The reason was absence information about birth date of test user. We updated the tests: if user birth date is absent we don't checks it presence.

Work of all other E2E tests was checked. They work correctly. 
Issue has been done.

**Comment by kuvakina** [comment]
Tests were updated according to the latest changes and work correctly in Jenkins.

@tony-shannon @PhilBarrett
