### ISSUE TITLE
RSS feed Cors.io

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#63]
When I log into Helm, the feeds module doesn't load.

**Comment by PhilBarrett** [comment]
![Screen Shot 2018-10-31 at 08.58.34.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236457f26b7191a378e70c2e59415c4abe5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecc58ff4ce84e56ac113e6af43b.png)
![Screen Shot 2018-10-31 at 09.08.00.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236457f26b7191a378e60c2b59415f4ebe5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5f35aa984ecc58ff4ce84e56ac113561f43b.png)

**Comment by BogdanScherban** [comment]
@robtweed  Rob, could you please help with this issue.

Maybe you remember, that we had problems with cross-domain requests for Feeds. 
Later you suggested to solve this problem by adding 'https://cors.io/?' in front of request:

![screenshot from 2018-11-01 15-47-05](https://user-images.githubusercontent.com/39263134/47855483-68cc3080-dded-11e8-9c37-fea08b01ce61.png)

But now we have problem with CORS again... 
We don't change client side of this request.

**Comment by PhilBarrett** [comment]
@kuvakina PR merged, will review with latest build on 8000 before closing

**Comment by PhilBarrett** [comment]
Checked also, working fine.
