### ISSUE TITLE
Staging.myhelm.org/null error

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#64]
Needs investigation for this error. See screenshot

**Comment by PhilBarrett** [comment]
![Screen Shot 2018-10-31 at 09.08.00.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236457f26b7191a378e60c2b59415f4ebe5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecc58ff4ce8495ca6123464f43b.png)

**Comment by PhilBarrett** [comment]
![Screen Shot 2018-10-31 at 08.58.34.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236457f26b7191a378e70c2e59415c4abe5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecc58ff4ce84857a7113e6af43b.png)
![Screen Shot 2018-10-31 at 09.08.00.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236457f26b7191a378e60c2b59415f4ebe5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecc58ff4ce84857a7173360f43b.png)

**Comment by BogdanScherban** [comment]
@PhilBarrett @robtweed 
I tried to find a reason of this problem. I have a assumption it is related with Feeds-problem:
https://github.com/LeedsCC/Helm-PHR-Project/issues/63

Why? Lets compare two cases. 

Case 1: RSS-request for Feeds was sent. We can see problem with NULL in Console
![01 - null](https://user-images.githubusercontent.com/39263134/47856873-ea718d80-ddf0-11e8-8517-5578a44f6b6f.png)

Case 2: RSS-request for Feeds wasn't sent. Error with /null is absent:
![02 - no null](https://user-images.githubusercontent.com/39263134/47857048-594ee680-ddf1-11e8-9b4a-294863c33bab.png)

Probably, when we'll find a reason of Feeds-request error, this issue will be fixed too.

**Comment by BogdanScherban** [comment]
This issue has been done. 

The reason was in trying to open image URL (which isn't showed in current version.

We added:
1) theme settings: is we show page synopsis images?
2) checking this setting in Synopsis componen

**Comment by PhilBarrett** [comment]
Thanks @kuvakina , I've not seen since either, closing out.
