### ISSUE TITLE
Hide user admin page in Helm PHR

### ISSUE THREAD

**Issue by kuvakina** [LeedsCC/Helm-PHR-Project#66]
The user admin page should be generally hidden in Helm PHR.

Users shouldn't see this info: https://www.screencast.com/t/xmgkAsxf

**Comment by BogdanScherban** [comment]
This issue has been done.

New parameter isShowUserAccountPage was added to theme settings.

User can pass to User Account page depends on value of this parameter.

By default isShowUserAccountPage = true.

**Comment by kuvakina** [comment]
User can't go to admin page in Helm PHR. See the video: https://www.screencast.com/t/QY37Kc4Vc

**Comment by PhilBarrett** [comment]
Checked, working fine. Thank you
