### ISSUE TITLE
As a user I need the ability to easily submit feedback/experience when using Helm.

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#82]
As a user I need the ability to easily submit comments when using Helm. 

At present there is a solution in use provided by Click4Assistance. We would like to recreate the behaviour where a user can click the feedback button (mobile and desktop) and enter the following information:

Header: "Comments"
**Name** (Mandatory) - Single text box
**Email** (Mandatory) - Single text box
**Phone number ** (Optional) - Single text box
**Please tell us the reason for your comment** (optional (Dropdown box))
           General Feedback
           Technical Issues
           Improvements
**Description** (please do not include any personal information. Comments viewed by admin only)

As a user, once I have completed and pressed submit for the comments, a confirmation screen is needed

API end points will be provided

**Comment by PhilBarrett** [comment]
https://docs.smartsurvey.io/docs/getting-started

**API Key and secret to be securely provided**

Fields:

"Full Name"                : Open-ended         Single textbox   Answer type: text
"Email"                         : Open-ended         Single textbox   Answer type:  text
"Phone number"      : Open-ended         Single textbox   Answer type:  text
"Feedback"                 : Open-ended         essay                     Answer type: comment
![SmartSurvey1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db999b3196b0bc9dffba5af51fbcd6395428792c07b7692ac7b62abe417e525a0949fe12095a10fcf98028f3bf3f25dc5919f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3b88e4ac3ee3f20ef888b482c53.png)
![SmartSurvey2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db999b3196b0bc9dffba5af61fbcd6395428792c07b7692ac7b62abe417e525a0949fe12095a10fcf98028f3bf3f25dc5919f1c32f0e2a92624cf5f2d75dad0ba8228b4584b3b88e4ac3ee3f23e48a874a2c53.png)

**Comment by simongamester** [comment]
@PhilBarrett I've added a mock up for this on InVision.

https://invis.io/6DNMOSUWX29

Also attached below:

![Support Modal.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb37967f01e4d00110fba95/125516c66e82c728ace21e0d46db818a338d91bdcfc4b047a551b2d86b56357c2301a03f32dfa17dbd4378045c5a18ab130b0e41a8f98922a5e33573df0a0effcd7f1d2598694ef1e1c84afd13b032894f8fb7b98e48c7e93c26e082884c3d0c48.png)

Please let me know your thoughts.

Simon

**Comment by simongamester** [comment]
@PhilBarrett Added screens for mobile version and thank you message.

https://invis.io/6DNMOSUWX29#/336877122_Support_Modal_-_Mobile

![Support Modal - Mobile.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb37967f01e4d00110fba95/125516c66e82c728ace21e0d46db818a338d91bdcfc4b047a551b0d9696b28712008a6693cc7f33ab0487e021b4d44be440a0e17a9fa8c7da1e46f218f080bedd86e0a7dc56847a9aa9e0dfd50e474d412dcfce9c85ecafa3c2ded8a8a4b3a19041089f85536a49b5985.png)

https://invis.io/6DNMOSUWX29

![Support Modal Thank You.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb37967f01e4d00110fba95/125516c66e82c728ace21e0d46db818a338d91bdcfc4b047a551b0a021472978693dac3e32c9a138ad4d71040c1b5ca6535d0d15afac8a2ef0b16e23db595fedd1645c21cf3e44fabd9003ad43eb7edf10d8eff6df0ed2e22f24e0818e4a3a1a021981fe5d37a59d43da15.png)

**Comment by tony-shannon** [comment]
looks good, though suggest we change 
sensitive --> personal

**Comment by PhilBarrett** [comment]
Thanks Tony.

@simongamester could you make this minor amend please.

**Comment by PhilBarrett** [comment]
@BogdanScherban Considering the shared secret as part of this, I assume this will need to be stored within QEWD, or is there a secure way to store the secret within PulseTile please. Our instinct is server side.

**Comment by PhilBarrett** [comment]
@BogdanScherban / @kuvakina Could you advise on earlier question please

**Comment by BogdanScherban** [comment]
@PhilBarrett 
Speaking honestly, I'm not fully understand why should be add shared secret here.. As I understand, this is a simple feedback form, which is presented in a lot of web-application, correct?

It is necessary to create required API route for adding feedback to the database at the server side.
If I understand correctly, it should be in QEWD.

**Comment by PhilBarrett** [comment]
Thanks @BogdanScherban . It's integrating with a secure survey tool, so an API key / shared secret is required I understand. @robtweed can this be handled in QEWD rather than PT layer?

**Comment by PhilBarrett** [comment]
Signed off screens
**Desktop** 
https://projects.invisionapp.com/share/6DNMOSUWX29#/screens/336846841
https://projects.invisionapp.com/share/6DNMOSUWX29#/screens/336877121

**Mobile**
https://projects.invisionapp.com/share/6DNMOSUWX29#/screens/336877122

**Comment by tony-shannon** [comment]
how about "Please tell us the reason for your comment"

**Comment by PhilBarrett** [comment]
OOS following rescope of Helm as instructed by LCC
