### ISSUE TITLE
Browser Cache Settings

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#83]
Requirement to not store browser cache.

Change HTML head of a page via the following tag: - <META HTTP-EQUIV='Cache-Control' CONTENT='no-cache, no-store'> HTTP 1.1. Allowed values = PUBLIC | PRIVATE | NO-CACHE | NO-STORE. - Public - may be cached in public shared caches. - Private - may only be cached in private cache. - No-Cache - may not be cached. - No-Store - may be cached but not archived.

**Comment by tony-shannon** [comment]
@PhilBarrett to provide update on this please

**Comment by tony-shannon** [comment]
This requirements comes from Pen test issue #SC-1489, sev 2 issue to be fixed
Fix is detailed above

**Comment by tony-shannon** [comment]
@kuvakina can you please advice inc relationship to cookies etc

**Comment by kuvakina** [comment]
sorry @tony-shannon could you please provide a bit more details to this issue?

**Comment by PhilBarrett** [comment]
Moved onto https://github.com/LeedsCC/Helm-PHR-Project/issues/99
