### ISSUE TITLE
Feeds not loading

### ISSUE THREAD

**Issue by kuvakina** [LeedsCC/Helm-PHR-Project#87]
On http://dev.ripple.foundation:8000 Feeds are not loading.
Assume that problem in cross-domain requests: https://www.screencast.com/t/NlxlcU2mwvS6

Also, noticed one thing. All Feeds has Remote Address: 217.198.117.111:443 .
Tried to go to this address but got this error message:

400 Bad Request
The plain HTTP request was sent to HTTPS port

**Comment by tony-shannon** [comment]
@simongamester could you take a look at this in our helm dev environment please
CORS related issue and Rob T suggested you may be able to help

T

**Comment by BogdanScherban** [comment]
The issue has been fixed

**Comment by kuvakina** [comment]
The issue with RSS-feeds displaying was fixed by using another proxy-server for CORS: 
const CORS_PROXY = "https://cors-anywhere.herokuapp.com/";

**Comment by tony-shannon** [comment]
ok this CORS solution may be blocked in future for security reasons, we need to consider other ways that we can get around this, who can investigate? i

**Comment by BogdanScherban** [comment]
@tony-shannon 
This solution - to use some proxy server for Feeds CORS - was suggested by @robtweed in June of last year. 
Unfortunately, this is temporary solution. It will work until https://cors-anywhere.herokuapp.com/ is available. But this is only one way, how I can solve this issue from frontend side.

Probably, we can try to run this request via server-path like:
we run API-request to QWED for rss-feeds ---->
----> QWED run request to Feeds source (BBC, NYT etc.) with all required headers ---->
----> QWED return response with feeds

**Comment by PhilBarrett** [comment]
@kuvakina We don't want to lose Feeds functionality, so please can a new task be created to add to the Showcase stack in case required in the future.

**Comment by kuvakina** [comment]
@PhilBarrett added a new issue https://github.com/RippleOSI/Ripple-Showcase-Stack-Project/issues/11

**Comment by PhilBarrett** [comment]
Awaiting user metadata, should be closed for now
