### ISSUE TITLE
nginx config

### ISSUE THREAD

**Issue by tony-shannon** [LeedsCC/Helm-PHR-Project#88]
nginx config needs updating for pen test sev 2 issues

**Comment by kuvakina** [comment]
@PhilBarrett Could you please give access to the doc?

**Comment by tony-shannon** [comment]
Helm nginx config should be mirrored on the Helm Dev servers in Digital Ocean

**Comment by tony-shannon** [comment]
parking for now, until we will revisit when safe to do so

**Comment by PhilBarrett** [comment]
Relates to https://github.com/LeedsCC/Helm-PHR-Project/issues/92
