### ISSUE TITLE
Forgotten password screen isn't rendering correctly

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#89]

**Comment by PhilBarrett** [comment]
![Screen Shot 2019-01-31 at 15.55.29.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77226457f26b7191a379ea0c2e54415d47be5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5f35aa984ecc50ff4ee14f55a6103360f43b.png)

**Comment by kuvakina** [comment]
There we have to fix styles. 
Also the same problem with login: https://www.screencast.com/t/misn5mYx36nr

**Comment by PhilBarrett** [comment]
This relates to NGINX changes investigation #92

**Comment by kuvakina** [comment]
Changed passwords for both **staging** and **helm-dev**:

for https://staging.myhelm.org -- problems with styles didn't appear, changes password successfully.  The only thing is that there is old functionality for creating password. 

for https://helm-dev.ripple.foundation -- problems with styles didn't appear, changes password successfully.

**Comment by PhilBarrett** [comment]
Closing this off  as on PT-R and working fine
