### ISSUE TITLE
Can't logout from staging.myhelm.org

### ISSUE THREAD

**Issue by kuvakina** [LeedsCC/Helm-PHR-Project#90]
when I logout i see nothing after: https://www.screencast.com/t/6426gfgItM
and URL is: https://staging.myhelm.org/openid/session/end?id_token_hint=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkZyajJ5VDNkVjlQdFVmYTdvQS1fREhybHZ0Tm5JaGE1N2FMTzhHXy1BZVUifQ.eyJlbWFpbCI6ImEua3V2YWtpbmFAcGlvZ3JvdXAubmV0IiwibmhzTnVtYmVyIjo5OTk5OTk5MDA2LCJmaXJzdE5hbWUiOiJBbGV4YW5kcmEiLCJsYXN0TmFtZSI6Ikt1dmFraW5hIiwibW9iaWxlTnVtYmVyIjoiKzM4MDY3NzE4NSA3MTMiLCJkb2IiOiIwMS8wMS8yMDAxIiwidm91Y2hlZEJ5IjoiUGhpbCBCYXJyZXR0Iiwic3ViIjo0LCJhdF9oYXNoIjoiNEdrQlZTYmd3djVUaDlMcDZtWmpDUSIsInNpZCI6ImNkNTEzOGUxLTA2YjQtNGI4Ny1hMmQyLWI0NWMxNDU4NGZiNyIsImF1ZCI6ImZvbyIsImV4cCI6MTU0OTAyMjM5MSwiaWF0IjoxNTQ5MDE4NzkxLCJpc3MiOiJodHRwczovL3N0YWdpbmcubXloZWxtLm9yZzo0NDMvb3BlbmlkIn0.F7mbf4gELWR6hC0aQIJzvNvZWWWJ3ZCAFwlZmKiIIp2myDk73_Ct6qeJ6dQMn0yRil-wKhJZN9EdZdeBdZ_MtlkTi5MPqE-Vd4fef--zimuFqiGoZ863psyxOlxZPtjPRMqZxGIwSsEFN7-353e3rPCy2ks_bIYUhpxU_oAEUPU63-HvY3dOznFQownWMdfFj-ixr1_6dma75-7rn-ANi2LVuYBNAjF27C-dwPn0n7Ag68htHiQhEarJSlJRq4_yTAfM_ejg3f3f37luQrzsCeC4n0kZwZ3UEiFM4BXbmnfRRDZ1xY0L604KrJjsFYRc4flfic7_Q3-PMPoQuf3yew&post_logout_redirect_uri=https://staging.myhelm.org:443

And when you delete this URL, and type the address: https://staging.myhelm.org, you are again on your personal page, that means that we wasn't logout. You have to make hard reset to logout.

**Comment by tony-shannon** [comment]
Rob has confirmed this issue is resolved, related to nginx changes now reversed

See more here
https://waffle.io/RippleOSI/combined-development-view/cards/5c52e4d60f6d750539e34f21
