### ISSUE TITLE
Issue with cookie (Home page)

### ISSUE THREAD

**Issue by kuvakina** [LeedsCC/Helm-PHR-Project#93]
On https://helm-dev.ripple.foundation and also on staging/prod, we noticed next:

when you click on settings icon: https://www.screencast.com/t/PLFqtqsawQ
and when you choose only some issues to show - you would see which you have chosen. 

But when you reload the page or go to another page and then back - you'd see default issues.

@PhilBarrett suggested, that we need a cookie or similar

**Comment by tony-shannon** [comment]
need to decide if we are storing these values in the browser (can be easily reset with reloading of page, so not ideal) or server (needs more work on MPI/user preferences)

**Comment by tony-shannon** [comment]
Q about Cookie.. how much can store & for how long, as we have a problem with clearing Cookies

**Comment by tony-shannon** [comment]
Q about how to clear cookies as well please

**Comment by tony-shannon** [comment]
JWT errors etc need way to clear cookies easily

**Comment by tony-shannon** [comment]
should be way to do garbage collection of cookies better

**Comment by PhilBarrett** [comment]
Descoped by LCC- Not in scope
