### ISSUE TITLE
Feeds should be a default

### ISSUE THREAD

**Issue by kuvakina** [LeedsCC/Helm-PHR-Project#94]
On https://helm-dev.ripple.foundation Feeds not available.

this happens when the user doesn't have any Feed, he gets an empty response: https://www.screencast.com/t/Et9MkfQx and that's why he doesn't see Feeds.

But feeds should be as default -  every new patient should have a feeds record on registration.

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett upd on issue:

the problemis the next: if nhsNumber already exists in the system then Feeds won't be shown. If nhsNumber doesn't exist in the system then Feeds would be loaded.

We can't tell why it's working this way, maybe @robtweed could help with it?

**Comment by kuvakina** [comment]
**UPD 19, Feb 2019** :

I've changed nhsNumber from 9999999008 to 96348091108, and now I can see Feeds: https://www.screencast.com/t/rPcxBA5glbiv

It's the same that Rob explained to Dima:
" _In OIDC-admin you specify the NHS Number for a user. If that NHS Number does not yet exist on the EtherCIS system, then QEWD-Courier will issue an OpenEHR request to create that user on the EtherCIS server, and THEN it will create a new set of default feeds for that new user. This ONLY happens when the NHS Number is first created on EtherCIS_ "

@tony-shannon @PhilBarrett I assume, that this problem with Feeds won't accure when would be created new users (as they would have new and original NHS Number).  So I don't think we should change the logic of this functionality, at this moment, at least.

**Comment by PhilBarrett** [comment]
Closing this issue as now out of scope for the Helm project at this time
