### ISSUE TITLE
myHelm title bar

### ISSUE THREAD

**Issue by tony-shannon** [LeedsCC/Helm-PHR-Project#96]
myHelm missing in browser title bar

**Comment by tony-shannon** [comment]
https://snag.gy/G6PyUn.jpg

see screenshot

**Comment by PhilBarrett** [comment]
Should be Helm, not myHelm

**Comment by kuvakina** [comment]
"myHelm" on login part, and if i'm correct this is a part where Simon works

**Comment by kuvakina** [comment]
"myHelm" on login part, and if i'm correct this is a part where Simon works

**Comment by PhilBarrett** [comment]
Resolved
