### ISSUE TITLE
Github Security vulnerability check

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#97]
We found a potential security vulnerabilty in one of your dependencies

We found a potential security vulnerability in a repository for which you have been granted security alert access.

Image removed by sender. @LeedsCC

LeedsCC/Helm-PHR-Generator

Known low severity security vulnerability detected in lodash < 4.17.11 defined in package-lock.json.

package-lock.json update suggested: lodash ~> 4.17.11.

**Comment by tony-shannon** [comment]
please check PulseTile RA repo also

**Comment by BogdanScherban** [comment]
@tony-shannon 

LeedsCC/Helm-PHR-Generator doesn't use lodash generally:
https://github.com/LeedsCC/Helm-PHR-Generator/blob/master/package.json

I updated dependencies in package.json in https://github.com/PulseTile/PulseTile-RA - could you please check - is vulnerability message presented?
