### ISSUE TITLE
Clear cookies and cache when tab/browser closed

### ISSUE THREAD

**Issue by kuvakina** [LeedsCC/Helm-PHR-Project#99]
Check this with Bogdan and Dima

also 

Requirement to not store browser cache.

Change HTML head of a page via the following tag: - HTTP 1.1. Allowed values = PUBLIC | PRIVATE | NO-CACHE | NO-STORE. - Public - may be cached in public shared caches. - Private - may only be cached in private cache. - No-Cache - may not be cached. - No-Store - may be cached but not archived.

**Comment by kuvakina** [comment]
The idea is to clear cookies and caches when user log out from the app:
1) when user sign out himself (by clicking Sign out button);
2) when user sign out forcefully after <1h>.

I think clear cookies and caches in the first case won't be a problem. But we have to think of the way how to do it (in the best way) for the second case. Especially, when user close app/browser before he could log out (himself or forcefully).

I suggested the variant, where cookies and caches are cleared automatically when user close tab or browser. What is your opinion re this @BogdanScherban ?

**Comment by tony-shannon** [comment]
>  Also, @tony-shannon @PhilBarrett I just thought of one thing: if we would clear cookies, each time user log in, he should accept T&C. Is it ok?
Perhaps for now, though we should store this server side soon.. another case for a Helm MPI @PhilBarrett

**Comment by BogdanScherban** [comment]
@tony-shannon @kuvakina 

I can't repeat the problem at my local-machine or at helm-dev. 
Please, show me the video of error with opened console.

PulseTile-ReactJS has error handling. In described case, server should return error with code 400 and one of these messages:
_'Authorization Header missing or JWT not found in header (expected format: Bearer {{JWT}}',
'Invalid JWT: Error: Token expired',
'Invalid JWT: Error: No token supplied'_ 

In this case modal window appears with the message 'Your session has expired. Click the button to log in again' and button to relogin.

**Comment by PhilBarrett** [comment]
Linked with https://github.com/LeedsCC/Helm-PHR-Project/issues/83

**Comment by BogdanScherban** [comment]
This issue has been done.

If any response to server is unsuccessful, modal window with message should be appeared.
Depending on error type it suggests user to relogin or reload page.

![image](https://user-images.githubusercontent.com/39263134/55171668-778ef780-5181-11e9-92ae-0d0597a9a44e.png)
![image](https://user-images.githubusercontent.com/39263134/55171901-de141580-5181-11e9-82d1-eb0a6bafaec6.png)

During relogin/reload session and local storages will be cleaned.
